project_id = "mifxyolxisssbtqmoacm"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[auth]
enabled = true
site_url = "https://tiamobew.github.io/math-farm/"
additional_redirect_urls = ["http://localhost:8000", "http://127.0.0.1:8000"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.register-student]
verify_jwt = false
